const chatData = {
  "xin chào": "Chào bạn iu, dễ thương quá đi 🐰💖",
  "chào": "Hiiiii 🌸 có tui đây nè 💕",
  "hi": "Hiii, bạn khỏe hong ✨",
  "hello": "Hello bé iu 🐻💓",
  "bye": "Bye bye cutiii, nhớ tui nha 🌙😘",
  "tạm biệt": "Tạm biệt, mai gặp lại nhen 🌸💖",
  "cảm ơn": "Cảm ơn bạn dễ thương ghê 💞🌷",
  "thanks": "Thanks nha, iu bạn nhiều 🐰💓",
  "xin lỗi": "Hong sao đâu, tui thương bạn lắm 🐧✨",
  "sorry": "Tha lỗi cho bạn luôn 🤗💖",
  "iu": "Iuuu bạn nhiều nhiều 💘🐰",
  "yêu": "Tui yêu bạn nè 🥺💕",
  "thương": "Thương quá chừng luôn 🐻💓",
  "nhớ": "Tui nhớ bạn lắm lun á 😭💖",
  "crush": "Crush dễ thương ghê 🌸💘",
  "cưng": "Cưng quá đi nè 🐰✨",
  "cute": "Bạn cute hột me quá 😍💞",
  "dễ thương": "Bạn dễ thương như thiên thần 👼💓",
  "xinh": "Xinh như hoa 🌷💖",
  "đẹp": "Đẹp rạng ngời luôn 🌟💓",
  "đỉnh": "Đỉnh của chóp ✨😎",
  "ngầu": "Ngầu như soái ca 🕶️💘",
  "vui": "Vui vẻ lên nhen 🌸🐰",
  "buồn": "Đừng buồn nữa, tui ôm bạn nè 🤗💖",
  "khóc": "Khóc đi rồi tui dỗ 🐻💞",
  "cười": "Cười lên nào, dễ thương lắm 😍✨",
  "haha": "Haha vui ghê 😂🌸",
  "hehe": "Hehe đáng yêu quá 🤭💕",
  "hihi": "Hihi xinh xỉu 🐰💖",
  "trời ơi": "Trời ơi cưng quá 😱💞",
  "ôi": "Ôi bất ngờ dễ sợ 😲✨",
  "wow": "Wowww xinh quá nè 🌟💘",
  "omg": "Ôi my gớt 😱🐰",
  "game": "Chơi game vui vẻ nha 🎮💖",
  "ăn": "Ăn nhiều cho khoẻ nha 🍜🍓",
  "uống": "Uống nước nhớ giữ gìn sức khoẻ 💧✨",
  "ngủ": "Đi ngủ sớm cho đẹp da nha 💤💖",
  "mơ": "Chúc bạn mơ đẹp 🌙💘",
  "học": "Học chăm vô, tui tin bạn 🐰📚",
  "thi": "Thi cử may mắn nhen 🍀✨",
  "trúng": "Trúng quà to nè 🎁💖",
  "trà sữa": "Trà sữa thêm trân châu hong 🧋💕",
  "cà phê": "Uống cà phê cho tỉnh táo ☕💖",
  "bánh": "Ăn bánh ngọt ghê 🍰✨",
  "kẹo": "Ngọt như kẹo mà cũng như bạn 🍭💞",
  "kem": "Kem lạnh mà tim thì ấm 💓🍦",
  "pizza": "Pizza nóng hổi vừa thổi vừa ăn 🍕🔥",
  "phở": "Phở ngon tuyệt cú mèo 🍜💖",
  "bún": "Bún riêu hay bún bò đây 😋💕",
  "cơm": "Ăn cơm cho chắc bụng 🍚✨",
  "cháo": "Cháo nóng cho ngày mưa 🌧️💞",
  "hoa": "Một bông hoa tặng bạn 🌹💖",
  "hoa hồng": "Hoa hồng đỏ như tình tui 💘🌹",
  "hoa sen": "Sen tinh khiết như bạn 🌸💞",
  "hoa đào": "Hoa đào mùa xuân xinh 🌸✨",
  "hoa mai": "Mai vàng rực rỡ 🎋💖",
  "trăng": "Trăng sáng dịu dàng 🌕💘",
  "sao": "Bạn sáng như sao ⭐✨",
  "trời": "Trời xanh trong ghê ☀️💓",
  "nắng": "Nắng vàng rực rỡ 🌞💖",
  "mưa": "Mưa rơi nhưng tui che cho ☔💕",
  "gió": "Gió mát lành 🌬️💞",
  "tuyết": "Tuyết trắng xinh ❄️⛄",
  "biển": "Biển xanh bao la 🌊💓",
  "núi": "Núi cao hùng vĩ ⛰️✨",
  "sông": "Sông nước hiền hoà 🏞️💖",
  "rừng": "Rừng xanh bí ẩn 🌲💕",
  "cỏ": "Cỏ xanh mát mắt 🌱💓",
  "cây": "Cây xanh bóng mát 🌳✨",
  "lá": "Chiếc lá vàng rơi 🍂💖",
  "trái tim": "Gửi bạn một trái tim 💖🐰",
  "tim": "Tim tui thuộc về bạn 💕✨",
  "yêu đời": "Yêu đời nhiều hơn nhen 🌸💞",
  "hạnh phúc": "Chúc bạn luôn hạnh phúc 💓🌟",
  "may mắn": "May mắn bên bạn 🍀✨",
  "sức khoẻ": "Chúc bạn nhiều sức khoẻ 💪💞",
  "thành công": "Thành công rực rỡ nha 🏆💖",
  "tương lai": "Tương lai sáng ngời 🌟✨",
  "ước mơ": "Mơ ước sẽ thành sự thật 💓🌸",
  "niềm tin": "Tin vô chính mình nhen 🐰💞",
  "hi vọng": "Hi vọng sẽ đến 💫💖",
  "cố lên": "Cố lên bạn ơi 💪🐰",
  "đừng bỏ cuộc": "Đừng bỏ cuộc, tui tin bạn 💓✨",
  "ôm": "Ôm ôm nè 🤗💞",
  "hun": "Hun cái nè 😘💘",
  "thơm": "Thơm má bạn một cái 💕🐰",
  "nắm tay": "Nắm tay nhau hong ✨💓",
  "cùng nhau": "Cùng nhau vượt qua 💞🐻",
  "đi chơi": "Đi chơi hong 🐰🎡",
  "shopping": "Đi mua sắm thôi 🛍️💖",
  "du lịch": "Đi du lịch cùng tui ✈️💕",
  "xe": "Xe chạy vù vù 🚗💨",
  "tàu": "Tàu chạy xình xịch 🚆💞",
  "máy bay": "Máy bay bay cao ✈️✨",
  "thuyền": "Thuyền trôi trên sông 🚤💓",
  "tên lửa": "Tên lửa vút bay 🚀💞",
  "vũ trụ": "Vũ trụ bao la 🌌✨",
  "thiên hà": "Thiên hà lung linh 🌠💓",
  "hành tinh": "Hành tinh xanh 🌍💖",
  "ngân hà": "Ngân hà sáng rực 🌌💞",
  "vũ công": "Nhảy múa cùng nhạc 💃✨",
  "ca sĩ": "Hát ca thật hay 🎤💓",
  "diễn viên": "Đóng phim đỉnh ghê 🎬💞",
  "họa sĩ": "Vẽ tranh thật đẹp 🎨💖",
  "nhạc sĩ": "Sáng tác nhạc hay ghê 🎶✨",
  "bác sĩ": "Chăm sóc bệnh nhân 👩‍⚕️💞",
  "y tá": "Y tá dễ thương ghê 💉💓",
  "kỹ sư": "Kỹ sư xây nhà 🏗️✨",
  "giáo viên": "Dạy dỗ tận tâm 📚💖",
  "học sinh": "Học sinh ngoan ngoãn 🎒💞",
  "bạn bè": "Bạn bè mãi mãi 👭💓",
  "bestie": "Bestie 4ever 💕🐰",
  "anh": "Anh đẹp trai ghê 😎💘",
  "chị": "Chị xinh như hoa 🌸💓",
  "em": "Em dễ thương quá 🐰💞",
  "ba": "Ba tuyệt vời 👨💖",
  "mẹ": "Mẹ là số 1 👩💞",
  "gia đình": "Gia đình hạnh phúc 👨‍👩‍👧‍👦💓",
  "anh hùng": "Anh hùng mạnh mẽ 💪✨",
  "siêu nhân": "Siêu nhân cứu thế giới 🦸‍♂️💖",
  "công chúa": "Công chúa xinh xắn 👑🌸",
  "hoàng tử": "Hoàng tử đẹp trai 🐰💘",
  "vua": "Vua uy nghi 👑💞",
  "nữ hoàng": "Nữ hoàng quyền lực 👑✨",
  "thần tiên": "Thần tiên giáng trần 👼💓",
  "ma thuật": "Phép thuật lung linh ✨🔮",
  "phù thủy": "Phù thủy bí ẩn 🧙‍♀️💞",
  "rồng": "Rồng bay lượn ghê 🐉🔥",
  "phượng hoàng": "Phượng hoàng tái sinh 🔥✨",
  "ngựa": "Ngựa chạy nhanh 🐎💓",
  "mèo": "Meow meow 🐱💕",
  "chó": "Gâu gâu 🐶💖",
  "thỏ": "Bunny cute 🐰💞",
  "gấu": "Ôm gấu nè 🐻💘",
  "cá": "Bơi tung tăng 🐟✨",
  "chim": "Chim hót líu lo 🐦💓",
  "ong": "Ong chăm chỉ 🐝💖",
  "bướm": "Bướm bay lung linh 🦋💞",
  "khủng long": "Khủng long to đùng 🦖✨",
  "máy tính": "Công nghệ xịn ghê 💻💓",
  "điện thoại": "Điện thoại reo ting ting 📱💖",
  "internet": "Online suốt luôn 🌐✨",
  "facebook": "Mạng xã hội chill ghê 👍💓",
  "youtube": "Xem video vui ghê ▶️💞",
  "tiktok": "TikTok nhảy nhót 🎶💃",
  "zalo": "Chat Zalo không? 💬💖",
  "game thủ": "Game thủ đỉnh ghê 🎮✨",
  "idol": "Idol dễ thương ghê 🌸💓",
  "fan": "Fan chân chính 🐰💘",
  "bánh mì": "Bánh mì Việt Nam ngon ghê 🥖💖",
  "xôi": "Xôi nóng hổi 🍙💞",
  "bánh bao": "Bánh bao nhân thịt 🥟💓",
  "chè": "Chè ngọt mát 🍧💖",
  "bún chả": "Bún chả Hà Nội thơm ghê 🍜✨",
  "nem": "Nem rán giòn tan 🥢💞",
  "lẩu": "Lẩu nóng hổi 🍲💓",
  "bia": "Bia mát lạnh 🍺✨",
  "rượu": "Rượu nồng ghê 🍶💞",
  "nước ngọt": "Uống coca cho mát 🥤💓",
  "cam": "Cam chua ngọt 🍊💖",
  "táo": "Táo đỏ giòn 🍎✨",
  "nho": "Nho tím mọng 🍇💞",
  "chuối": "Chuối vàng thơm 🍌💓",
  "dưa hấu": "Dưa hấu đỏ 🍉💖",
  "xoài": "Xoài ngọt 🍋✨",
  "ổi": "Ổi giòn 🥭💞",
  "dâu": "Dâu tây đỏ 🍓💓",
  "coconut": "Dừa mát lạnh 🥥💖",
  "thơ": "Làm thơ tặng bạn ✍️💕",
  "nhạc": "Nghe nhạc thư giãn 🎧✨",
  "phim": "Xem phim chill 🎬💓",
  "truyện": "Đọc truyện tranh 📖💞",
  "sách": "Sách hay ghê 📚💖",
  "báo": "Đọc báo mỗi ngày 📰✨",
  "tin tức": "Tin nóng hổi 📢💞",
  "thời tiết": "Nắng mưa thất thường ☀️🌧️",
  "giáng sinh": "Merry Christmas 🎄🎅",
  "tết": "Tết sum vầy 🎆🎉",
  "sinh nhật": "Happy Birthday 🎂🎁",
  "valentine": "Valentine ngọt ngào 💘🍫",
  "noel": "Noel an lành 🎄💖",
  "halloween": "Halloween ma mị 🎃👻",
  "trung thu": "Trung thu trăng sáng 🏮🐰",
  "quốc khánh": "Mừng Quốc Khánh 🎉🇻🇳",
  "30/4": "Ngày giải phóng 30/4 🇻🇳✨",
  "2/9": "Quốc khánh 2/9 🇻🇳💖",
  "8/3": "Chúc mừng ngày 8/3 🌸💐",
  "20/10": "Ngày phụ nữ Việt Nam 💖🌷",
  "1/6": "Ngày quốc tế thiếu nhi 🎉🐻",
  "20/11": "Ngày nhà giáo VN 👩‍🏫📚",
  "14/2": "Valentine tình yêu 💘✨",
  "24/12": "Đêm Giáng Sinh 🎄🌟",
}:
function getReply(input) {
  input = input.toLowerCase();
  for (let key in chatData) {
    if (input.includes(key)) {
      return chatData[key];
    }
  }
  return "Tui hong hiểu bạn nói gì 🐰💭";
}
